import Link from "next/link";
import type { CircuitRace,LayoutTopology } from "@/lib/circuit-history";
const seconds=(s:string|null)=>s?s.split(":").reduce((total,part)=>total*60+Number(part),0):NaN;
const num=(v:number|null|undefined,suffix="",digits=1)=>typeof v==="number"?`${v.toLocaleString("es-AR",{maximumFractionDigits:digits})}${suffix}`:"—";
export function CircuitLayoutFacts({races,turns,profile}:{races:CircuitRace[];turns?:number;profile?:LayoutTopology}){
  const records=races.filter(r=>r.fastestTime&&Number.isFinite(seconds(r.fastestTime))).sort((a,b)=>seconds(a.fastestTime)-seconds(b.fastestTime));
  const record=records[0];
  const covered=races.filter(r=>r.weather);
  const wet=covered.filter(r=>r.weather!.rain>0.1);
  const facts:[[string,string],...[string,string][]]=[["Longitud",num(races[0]?.length," km",3)],["Curvas documentadas",num(turns,"",0)],["Récord de vuelta en carrera",record?.fastestTime??"—"],["Fechas de GP con precipitación estimada",covered.length?num(wet.length/covered.length*100,"%",1):"—"]];
  return <div className="circuit-layout-facts"><dl className="circuit-technical-grid">{facts.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd>{label==="Récord de vuelta en carrera"&&record?<small><Link href={record.href} prefetch={false}>{record.fastest.map(d=>d.name).join(" / ")} · {record.year} ↗</Link></small>:null}{label.startsWith("Fechas")?<small>{wet.length} de {covered.length} fechas con datos · cobertura {covered.length}/{races.length}</small>:null}</div>)}</dl><p className="history-note">Récord: menor vuelta rápida de carrera registrada en las ediciones de este trazado del archivo; no incluye pruebas ni otras categorías. La lluvia corresponde al día UTC completo, no confirma pista mojada durante la carrera.</p><h4>TelemetryOne · geometría de este trazado</h4>{profile?<><dl className="circuit-technical-grid">{[["Cambios de dirección detectados",num(profile.turnCount,"",0)],["Qué tan curvoso",num(profile.turnsPerKm," giros/km",2)],["Recta más larga estimada",num(profile.longestStraight," m",0)],["Chicanas detectadas",num(profile.chicanes,"",0)],["Secuencias de eses",num(profile.esses,"",0)],["Complejidad geométrica",num(profile.complexity===null?null:profile.complexity*100," / 100",0)],["Exposición a rectas",num(profile.straightExposure===null?null:profile.straightExposure*100," / 100",0)],["Giro acumulado",num(profile.totalTurningPerKm," °/km",0)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="history-note">Análisis v9 del dibujo histórico de {profile.year}: <a href={profile.source} target="_blank" rel="noreferrer">{profile.imageTitle.replace(/^File:/,"")} ↗</a>. Calidad geométrica {profile.quality==="high"?"alta":"media"}. Las detecciones del algoritmo son estimaciones; un cambio de dirección detectado no equivale necesariamente a una curva con nombre. Los índices describen la geometría, no el rendimiento del auto.</p></>:<p className="history-note">No hay una geometría histórica con calidad suficiente para publicar estas métricas. No se extrapola la configuración moderna a este trazado.</p>}</div>;
}
