import Link from "next/link";
import { SiteHeader } from "./SiteHeader";
import { SiteFooter } from "./SiteFooter";
import { CircuitLayoutFigure } from "./ArchiveImages";
import { CircuitPoleChart } from "./CircuitPoleChart";
import { getCircuitResults, type CircuitRace, type CircuitDriver } from "@/lib/circuit-history";
import type { HistoryEntity } from "@/lib/history";
import { LAYOUT_CREDIT, layoutSeasons } from "@/lib/circuit-layouts";
import { translate } from "@/lib/dictionary";
import { getCountryFlagUrl } from "@/lib/circuit-visuals";
import { CircuitLayoutFacts } from "./CircuitLayoutFacts";
import { CircuitLocationMap } from "./CircuitLocationMap";
import mapLines from "@/data/circuit-map-lines.json";
import stories from "@/data/circuit-stories.json";

type Story = { opened?: string; origin: string; history: string; source: string; revision?: number };
const texts: Record<string,Story> = stories;
const venueTypes: Record<string,string> = {RACE:"Autódromo",STREET:"Urbano",ROAD:"Carreteras públicas"};
const directions: Record<string,string> = {CLOCKWISE:"Horario",ANTI_CLOCKWISE:"Antihorario"};
const n = (v:number|null|undefined,suffix="") => typeof v==="number" ? `${v.toLocaleString("es-AR",{maximumFractionDigits:3})}${suffix}` : "—";
function DriverLinks({drivers}:{drivers:CircuitDriver[]}) {return drivers.length ? <>{drivers.map((d,i)=><span key={`${d.id}-${i}`}>{i?" / ":""}{d.href?<Link prefetch={false} href={d.href}>{d.name}</Link>:d.name}</span>)}</> : <>—</>;}
function RaceTable({races}:{races:CircuitRace[]}) {return <div className="history-table-scroll circuit-race-table" tabIndex={0} role="region" aria-label="Resultados por edición, desplazamiento horizontal"><table><thead><tr><th>Fecha</th><th>Gran Premio</th><th>Vueltas</th><th>Distancia</th><th>Pole</th><th>Tiempo de pole</th><th>Ganador</th><th>Tiempo de carrera</th><th>Vuelta rápida</th><th>Tiempo</th><th>Clima estimado · día UTC</th></tr></thead><tbody>{races.map(r=><tr key={`${r.year}-${r.round}`}><td>{new Intl.DateTimeFormat("es-AR",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${r.date}T12:00:00Z`))}</td><th scope="row"><Link prefetch={false} href={r.href}>{translate(r.name.replace(/^\d{4}\s+/,""),"races")} · {r.year} ↗</Link></th><td>{n(r.laps)}</td><td>{n(r.distance," km")}</td><td><DriverLinks drivers={r.pole?[r.pole]:[]} /></td><td>{r.poleTime??(r.poleFormat==="sprint"?"Decidida por sprint":"—")}{r.poleFormat==="four-laps"?<small>4 vueltas</small>:null}</td><td><DriverLinks drivers={r.winners}/></td><td>{r.winnerTime??"—"}</td><td><DriverLinks drivers={r.fastest}/></td><td>{r.fastestTime??"—"}</td><td>{r.weather?<span className="circuit-race-weather" title={`Reanálisis ERA5 · día UTC completo · ${r.weather.rain} mm acumulados · máximo horario ${r.weather.peakRain} mm/h`}><span aria-hidden="true">{r.weather.condition==="heavy"?"⛈":r.weather.condition==="rain"?"🌧":"○"}</span> {r.weather.condition==="heavy"?"Lluvia intensa":r.weather.condition==="rain"?"Lluvia":"Sin precipitación"}<small>{n(r.weather.temperature," °C")} · {n(r.weather.rain," mm")}</small></span>:"Sin cobertura"}</td></tr>)}</tbody></table></div>;}
export async function CircuitDossier({entity}:{entity:HistoryEntity}) {
  const data=await getCircuitResults();const races=data.circuits[entity.id]??[];const story=texts[entity.id];
  const venue=data.venues[entity.id];
  const layouts=entity.biography.layouts??[];
  const ids=[...new Set(races.map(r=>r.layoutId??"unknown"))];
  const comparable=races.filter(r=>r.pole&&r.winners.length);
  const conversions=comparable.filter(r=>r.winners.some(d=>d.id===r.pole?.id)).length;
  const wins=new Map<string,{driver:CircuitDriver;count:number}>();for(const r of races)for(const d of r.winners){const row=wins.get(d.id)??{driver:d,count:0};row.count++;wins.set(d.id,row);}
  const leaders=[...wins.values()].sort((a,b)=>b.count-a.count).slice(0,8);
  return <main id="top" className="inner-page history-page circuit-page"><SiteHeader/><div className="history-content">
    <header className="archive-head"><nav className="archive-crumb" aria-label="Ruta"><Link href="/historia?categoria=circuits#archivo">Circuitos</Link><span>/</span><span>{entity.name}</span></nav><div className="circuit-title-line">{getCountryFlagUrl(entity.country??"")?<img className="circuit-country-flag" src={getCountryFlagUrl(entity.country??"")} alt={translate(entity.country??"","countries")} width={60} height={40}/>:null}<h1>{entity.name}</h1></div><p className="archive-meta">{entity.fullName} · {translate(entity.country??"","countries")}</p><dl className="archive-figures">{[["Grandes Premios",races.length],["Temporadas",new Set(races.map(r=>r.year)).size],["Configuraciones en F1",ids.length],["Primera edición",races[0]?.year??"—"],["Última del archivo",races.at(-1)?.year??"—"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></header>
    <nav className="history-profile-nav" aria-label="Secciones del circuito"><a href="#historia">Historia</a><a href="#localizacion">Mapa</a><a href="#trazados">Trazados y carreras</a><a href="#palmares">Pilotos destacados</a><a href="#fuentes">Fuentes</a></nav>
    {venue ? <dl className="circuit-venue-facts"><div><dt>Localización</dt><dd>{venue.placeName} · {translate(entity.country??"","countries")}</dd></div><div><dt>Tipo del recinto</dt><dd>{venueTypes[venue.type]??venue.type}</dd></div><div><dt>Sentido de la vuelta</dt><dd>{directions[venue.direction]??venue.direction}</dd></div><div><dt>Ubicación en el mapa</dt><dd><a href={`https://www.openstreetmap.org/?mlat=${venue.latitude}&mlon=${venue.longitude}#map=14/${venue.latitude}/${venue.longitude}`} target="_blank" rel="noreferrer">{n(venue.latitude)}, {n(venue.longitude)} ↗</a></dd></div></dl> : null}
    <section id="historia" className="history-section"><h2>Origen e historia</h2>{story?.opened?<p className="circuit-opened">Apertura: <strong>{story.opened}</strong></p>:null}<div className="history-story">{story?<><p>{story.origin}</p><p>{story.history}</p></>:<p>La historia documental de este circuito está pendiente de revisión.</p>}<p>En el Campeonato Mundial, el archivo registra {races.length} Grandes Premios entre {races[0]?.year} y {races.at(-1)?.year}. Las configuraciones y tablas siguientes permiten seguir sus distintas etapas sin mezclar recorridos de diferente longitud.</p></div>{story?<p className="history-note">Historia redactada a partir de <a href={story.source} target="_blank" rel="noreferrer">Wikipedia ↗</a>{story.revision?<> · <a href={`https://en.wikipedia.org/w/index.php?oldid=${story.revision}`} target="_blank" rel="noreferrer">Revisión consultada ↗</a></>:null}.</p>:null}</section>
    {venue?<section id="localizacion" className="history-section"><h2>Localización y recorrido actual</h2><CircuitLocationMap latitude={venue.latitude} longitude={venue.longitude} name={entity.name} paths={(mapLines as Record<string,{paths:number[][][]}>)[entity.id]?.paths??[]}/></section>:null}
    <section id="trazados" className="history-section"><h2>Trazados y resultados por edición</h2><p className="history-note">Cada tabla reúne únicamente las carreras de esa configuración. Los enlaces abren el artículo de la carrera o la ficha del piloto.</p>{ids.map((id,layoutIndex)=>{const rows=races.filter(r=>(r.layoutId??"unknown")===id);const layout=layouts.find(l=>l.id===id);return <section key={id} className="circuit-layout-era"><h3>{entity.name} {layoutIndex+1} <span>· {layoutSeasons(id)||`${rows[0].year}–${rows.at(-1)?.year}`}</span></h3><p className="circuit-layout-meta">{id} · {n(layout?.length??rows[0].length," km")}{layout?.turns?` · ${layout.turns} curvas`:""}</p><CircuitLayoutFigure layoutId={id} alt={`Trazado de ${entity.name}, ${layoutSeasons(id)}`}><b>{layoutSeasons(id)}</b></CircuitLayoutFigure><CircuitLayoutFacts races={rows} turns={layout?.turns} profile={data.topology[id]}/><RaceTable races={rows}/><h4 className="circuit-chart-heading">Evolución de los tiempos de pole · {entity.name} {layoutIndex+1}</h4><CircuitPoleChart races={rows}/></section>;})}</section>
    <section id="palmares" className="history-section"><h2>Los pilotos en este circuito</h2><div className="circuit-highlights"><div><h3>Ganadores más frecuentes</h3><ol>{leaders.map(row=><li key={row.driver.id}><DriverLinks drivers={[row.driver]}/><strong>{row.count} {row.count===1?"victoria":"victorias"}</strong></li>)}</ol></div><div><h3>Victorias desde la pole</h3><strong className="circuit-conversion">{n(comparable.length?conversions/comparable.length*100:null,"%")}</strong><p>{conversions} victorias en {comparable.length} carreras con pole y ganador registrados. Describe el historial del circuito; no es una probabilidad de victoria para una carrera futura.</p></div></div></section>
    <section id="fuentes" className="history-section history-sources"><h2>Fuentes y criterios</h2><p className="history-note">Resultados de <a href="https://github.com/f1db/f1db" target="_blank" rel="noreferrer">F1DB · CC BY 4.0</a>, hasta {data.meta.through}. Pole: piloto registrado en la primera posición de la grilla; su tiempo de clasificación cuando está disponible. Las sanciones pueden cambiar quién obtiene la pole frente al más rápido de la sesión. En los sprint de 2021 la pole se decidió en una carrera y se deja sin tiempo de vuelta. Indianápolis 1950–1960 usa un registro de cuatro vueltas. Los tiempos de carrera no son tiempos de vuelta. «—» significa sin registro disponible. Los ganadores y vueltas rápidas compartidos se conservan.</p><p className="history-note">Clima: <a href="https://open-meteo.com/en/docs/historical-weather-api" target="_blank" rel="noreferrer">Open-Meteo / ERA5 ↗</a>, reanálisis regional, no medición en pista. Temperatura media del aire y precipitación del día UTC completo (24 horas). «Sin precipitación» no significa cielo despejado. Lluvia: más de 0,1 mm diarios; icono de intensidad alta: al menos una hora con 5 mm o más, criterio descriptivo de esta página. Porcentaje calculado solo sobre fechas con 24 horas completas; no equivale a carreras disputadas en lluvia. Geometría actual del mapa: OpenStreetMap, consulta 6 de octubre de 2026.</p><p className="history-note">Dibujos de trazados: <a href={LAYOUT_CREDIT.url}>{LAYOUT_CREDIT.label}</a>. <a href={entity.sources.statsf1} target="_blank" rel="noreferrer">Consultar StatsF1 ↗</a>{story?<> · <a href={story.source} target="_blank" rel="noreferrer">Historia en Wikipedia ↗</a></>:null}.</p></section>
  </div><SiteFooter/></main>;
}
