import Link from "next/link";
import {SiteHeader} from "./SiteHeader";
import {SiteFooter} from "./SiteFooter";
import {CircuitArticlePhoto} from "./CircuitArticlePhoto";
import {CircuitLayoutFigure} from "./ArchiveImages";
import {LinkedNarrative, tidy, type NarrativeTarget} from "./LinkedNarrative";
import {getCountryFlagUrl} from "@/lib/circuit-visuals";
import {translate} from "@/lib/dictionary";
import type {HistoryEntity} from "@/lib/history";
import {layoutDrawing,LAYOUT_CREDIT} from "@/lib/circuit-layouts";
import {getGrandPrixEditions,grandPrixArticles,grandPrixVenues,grandPrixVenuePhotos,editionYears,type GrandPrixVenue,type GrandPrixEdition,type HistoricalEdition} from "@/lib/grand-prix-history";
import "../app/grand-prix.css";

const gpNames:Record<string,string>={'70th-anniversary':'Gran Premio del 70.º Aniversario','abu-dhabi':'Gran Premio de Abu Dabi','emilia-romagna':'Gran Premio de Emilia-Romaña',styria:'Gran Premio de Estiria',tuscany:'Gran Premio de Toscana',indianapolis:'500 Millas de Indianápolis'};
const grandPrixHeading=(entity:HistoryEntity)=>gpNames[entity.id]??`Gran Premio de ${translate(entity.name,'countries')}`;
const external={target:"_blank",rel:"noreferrer"} as const;
const n=(value:number)=>value.toLocaleString("es-AR");
function Person({person}:{person:{name:string;href:string|null}}){return person.href?<Link prefetch={false} href={person.href}>{person.name}</Link>:<>{person.name}</>;}
function VenueLink({venue}:{venue:GrandPrixVenue}){return venue.circuitId&&venue.href?<Link prefetch={false} href={venue.href}>{venue.name} ↗</Link>:venue.href?<a href={venue.href} {...external}>{venue.name} ↗</a>:<>{venue.name}</>;}
function Coordinates({venue}:{venue:GrandPrixVenue}){return venue.latitude!==null&&venue.longitude!==null?<a href={`https://www.openstreetmap.org/?mlat=${venue.latitude}&mlon=${venue.longitude}#map=13/${venue.latitude}/${venue.longitude}`} {...external}>{venue.latitude.toFixed(4)}, {venue.longitude.toFixed(4)} ↗</a>:<span>Sin coordenadas verificadas</span>;}
function WorldTable({rows}:{rows:GrandPrixEdition[]}){return <div className="gp-table-scroll" tabIndex={0} role="region" aria-label="Ediciones del Mundial, tabla desplazable"><table><caption>Ediciones del campeonato mundial · más recientes primero</caption><thead><tr><th scope="col">Año y fecha</th><th scope="col">Sede</th><th scope="col">Ganador y constructor</th><th scope="col">Grilla P1 / clasificación</th><th scope="col">Vuelta rápida</th><th scope="col">Reporte</th></tr></thead><tbody>{[...rows].reverse().map(row=><tr key={row.href}><th scope="row"><Link prefetch={false} href={row.href}>{row.year}</Link><small>{new Date(row.date+"T12:00:00Z").toLocaleDateString("es-AR",{day:"numeric",month:"short",timeZone:"UTC"})}</small></th><td><Link prefetch={false} href={row.circuit.href??`/historia/circuits/${row.circuit.id}`}>{row.circuit.name} ↗</Link></td><td>{row.winners.map((winner,i)=><span key={winner.id}>{i>0?" / ":""}<Person person={winner}/></span>)}<small>{row.constructors.map((team,i)=><span key={team.id}>{i>0?" / ":""}<Link prefetch={false} href={team.href??`/historia/constructors/${team.id}`}>{team.name}</Link></span>)}{row.winnerTime?` · ${row.winnerTime}`:""}</small></td><td>{row.pole?<Person person={row.pole}/>:"—"}<small>{row.poleTime??"Sin tiempo registrado"}</small></td><td>{row.fastest.length?row.fastest.map((driver,i)=><span key={driver.id}>{i>0?" / ":""}<Person person={driver}/></span>):"—"}</td><td><details className="gp-row-report"><summary>Resumen</summary>{row.summary.map((text,i)=><p key={i}>{tidy(text.replace(/(?:19|20)\d{2} [A-Za-z -]+ Grand Prix/g, name=>name.slice(0,5)+translate(name.slice(5),"races")))}</p>)}{row.distance!==null?<p>Distancia: {row.distance.toLocaleString("es-AR")} km.</p>:null}</details><Link prefetch={false} href={row.href}>Reporte completo ↗</Link><small>{row.modelCount>0?"Incluye análisis TelemetryOne":"Resultados históricos"}</small></td></tr>)}</tbody></table></div>;}
const category=(value:string)=>({"sports car":"Deportivos","sports cars":"Deportivos",sportscar:"Deportivos","grand prix":"Grand Prix","formula libre":"Fórmula Libre","formula two":"Fórmula 2","formula one":"Fórmula 1","formula one/two":"Fórmula 1/2",voiturette:"Voiturettes","formula 2000":"Fórmula 2000","tasman formula":"Fórmula Tasman","formula atlantic":"Fórmula Atlantic","formula pacific":"Fórmula Pacific","touring cars":"Turismos",f3:"Fórmula 3"}[value.toLowerCase()]??value);
const historicalNote=(row:HistoricalEdition)=>row.note?.startsWith("Categoría registrada:")?`Categoría registrada: ${category(row.raceClass??"")}.`:row.note?.replace(/[A-Z][A-Za-z -]+ Grand Prix/g,name=>translate(name,"races"));
function HistoricalTable({rows,label}:{rows:HistoricalEdition[];label:string}){return <div className="gp-table-scroll" tabIndex={0} role="region" aria-label={`${label}, tabla desplazable`}><table><caption>{label} · orden cronológico</caption><thead><tr><th scope="col">Año</th><th scope="col">Ganador</th><th scope="col">Auto / fabricante</th><th scope="col">Sede</th><th scope="col">Contexto y crónica</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.year}/${row.eventTitle??""}`}><th scope="row">{row.year}</th><td>{row.winnerLinks.length?row.winnerLinks.map((driver,i)=><span key={`${driver.url}/${i}`}>{i>0?" / ":""}<a href={driver.url} {...external}>{driver.name}</a></span>):row.winners}</td><td>{row.vehicle??"—"}</td><td>{row.venueId&&grandPrixVenues[row.venueId]?<VenueLink venue={grandPrixVenues[row.venueId]}/>:row.location??"Sede no documentada"}</td><td>{row.eventTitle?<strong>{row.eventTitle}</strong>:null}{row.raceClass?<small>{category(row.raceClass)}</small>:null}{row.note?<p>{historicalNote(row)}</p>:null}<a href={row.report} {...external}>Crónica / referencia histórica ↗</a></td></tr>)}</tbody></table></div>;}

export async function GrandPrixDossier({entity}:{entity:HistoryEntity}){
 const data=await getGrandPrixEditions();const editions=data.grandsPrix[entity.id];const article=grandPrixArticles[entity.id];
 const yearsByVenue=new Map<string,{world:number[];historic:number[]}>();
 for(const row of editions.world){const item=yearsByVenue.get(row.circuit.id)??{world:[],historic:[]};item.world.push(row.year);yearsByVenue.set(row.circuit.id,item);}
 for(const row of editions.historical){if(!row.venueId)continue;const item=yearsByVenue.get(row.venueId)??{world:[],historic:[]};item.historic.push(row.year);yearsByVenue.set(row.venueId,item);}
 const venues=[...yearsByVenue].map(([id,years])=>({venue:grandPrixVenues[id],...years})).filter(row=>row.venue).sort((a,b)=>Math.min(...a.world,...a.historic)-Math.min(...b.world,...b.historic));
 const predecessors=editions.historical.filter(row=>row.year<1950&&!row.designation);const outside=editions.historical.filter(row=>row.year>=1950&&!row.designation);const honorary=editions.historical.filter(row=>row.designation);
 const drivers=(entity.relations.find(g=>g.category==='drivers')?.items??[]).filter(d=>d.wins>0).sort((a,b)=>b.wins-a.wins||a.firstSeason-b.firstSeason);
 const teams=(entity.relations.find(g=>g.category==='constructors')?.items??[]).filter(t=>t.wins>0).sort((a,b)=>b.wins-a.wins||a.firstSeason-b.firstSeason);
 const modelEditions=editions.world.filter(r=>r.modelCount>0).length;
 const flag=entity.country?getCountryFlagUrl(entity.country):null;
 const targets:NarrativeTarget[]=[...entity.relations.flatMap(group=>group.items.map(item=>({text:item.name,href:item.href}))),...venues.filter(v=>v.venue.href).map(v=>({text:v.venue.name,href:v.venue.href!})),...['monza','imola','silverstone','nurburgring'].flatMap(id=>grandPrixVenues[id]?[{text:id==='nurburgring'?'Nürburgring':id[0].toUpperCase()+id.slice(1),href:grandPrixVenues[id].href!}]:[])];
 const sections=[['historia','Historia'],['sedes','Sedes'],...(predecessors.length?[['antes-del-mundial','Antes de 1950']]:[]),...(outside.length?[['fuera-del-mundial','Otras ediciones']]:[]),...(honorary.length?[['titulo-honorifico','Título honorífico']]:[]),['ediciones','Mundial'],['telemetry','TelemetryOne'],['palmares','Palmarés'],['fuentes','Fuentes']];
 return <main id="top" className="inner-page history-page gp-page"><SiteHeader/><div className="history-content gp-content">
  <header className="archive-head"><nav className="archive-crumb" aria-label="Ruta"><Link href="/historia">Estadísticas</Link><span>/</span><Link href="/historia?categoria=grands-prix#archivo">Grandes Premios</Link></nav><p className="gp-eyebrow">HISTORIA DE UN EVENTO</p><h1>{flag?<img className="archive-flag" src={flag} alt="" width={36} height={24}/>:null}{grandPrixHeading(entity)}</h1><p className="archive-meta">{entity.country?translate(entity.country,'countries')+' · ':''}En el Mundial: {editionYears(editions.world.map(r=>r.year))}</p><dl className="archive-figures"><div><dt>Ediciones en el Mundial</dt><dd>{n(editions.world.length)}</dd></div><div><dt>Sedes documentadas</dt><dd>{n(venues.length)}</dd></div><div><dt>Ganadores en el Mundial</dt><dd>{n(drivers.length)}</dd></div><div><dt>Primera edición documentada</dt><dd>{Math.min(...editions.world.map(r=>r.year),...editions.historical.map(r=>r.year))}</dd></div></dl></header>
  <nav className="gp-nav" aria-label="Contenido del Gran Premio">{sections.map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav>
  <section id="historia" className="history-section gp-history"><h2>La historia del Gran Premio</h2>{article.chapters.map((chapter,i)=><details key={chapter.title} open className="gp-chapter"><summary><span>{String(i+1).padStart(2,'0')}</span><h3>{chapter.title}</h3></summary><LinkedNarrative text={chapter.text} targets={targets} counts={{}}/></details>)}{article.related.length?<p className="gp-further">Más información sobre eventos relacionados: {article.related.map((id,i)=><span key={id}>{i>0?' · ':''}<Link href={`/historia/grands-prix/${id}`}>{grandPrixArticles[id]?id==='sao-paulo'?'Gran Premio de São Paulo':id==='brazil'?'Gran Premio de Brasil':id==='san-marino'?'Gran Premio de San Marino':id==='emilia-romagna'?'Gran Premio de Emilia-Romaña':id==='japan'?'Gran Premio de Japón':'Gran Premio de Azerbaiyán':id} ↗</Link></span>)}</p>:null}</section>
  <section id="sedes" className="history-section"><h2>Dónde se corrió</h2><p className="gp-lead">Las sedes del evento y de sus antecedentes documentados. Las fechas indican carreras disputadas; una pausa no se interpreta como continuidad.</p><div className="gp-table-scroll" tabIndex={0} role="region" aria-label="Sedes y coordenadas, tabla desplazable"><table><caption>Sedes, etapas y ubicación</caption><thead><tr><th scope="col">Sede</th><th scope="col">En el Mundial</th><th scope="col">Antecedentes / otras ediciones</th><th scope="col">Coordenadas</th><th scope="col">Más información</th></tr></thead><tbody>{venues.map(({venue,world,historic})=><tr key={venue.id}><th scope="row"><VenueLink venue={venue}/></th><td>{world.length?editionYears(world):'—'}</td><td>{historic.length?editionYears(historic):'—'}</td><td><Coordinates venue={venue}/>{venue.coordinateScope!=='circuit'?<small>Punto de referencia de la sede o localidad</small>:null}<small><a href={venue.source} {...external}>Fuente de ubicación ↗</a></small></td><td>{venue.href?<VenueLink venue={venue}/>:"Sin artículo enlazado"}</td></tr>)}</tbody></table></div><p className="history-note">Las coordenadas históricas son puntos de referencia: no reconstruyen la línea de salida ni el recorrido de aquella edición. Para planos, cambios del trazado y datos técnicos, abrí el artículo del circuito.</p><div className="gp-venue-gallery">{venues.map(({venue,world,historic})=>{const photo=grandPrixVenuePhotos(venue)[0];const layoutId=venue.circuitId&&layoutDrawing(venue.circuitId+'-1')?venue.circuitId+'-1':null;return <article key={venue.id}><h3><VenueLink venue={venue}/></h3><p>{editionYears([...world,...historic])}</p>{photo?<CircuitArticlePhoto photo={photo}/>:layoutId?<CircuitLayoutFigure layoutId={layoutId} alt={`Referencia de un trazado de ${venue.name}; las versiones históricas están en el artículo del circuito.`}/>:null}<p className="gp-further">{venue.href?<><span>Más información:</span> <VenueLink venue={venue}/></>:null}</p></article>;})}</div></section>
  {predecessors.length?<section id="antes-del-mundial" className="history-section"><h2>Antes del campeonato mundial</h2><p className="gp-lead">{predecessors.length} ediciones documentadas anteriores a 1950. Utilizaban distintos reglamentos; no se presentan como temporadas de Fórmula 1.</p><HistoricalTable rows={predecessors} label="Ediciones anteriores a 1950"/></section>:null}
  {outside.length?<section id="fuera-del-mundial" className="history-section"><h2>Ediciones fuera del Mundial y otras categorías</h2><p className="gp-lead">Pruebas documentadas desde 1950, anteriores o intermedias a la etapa mundialista. Incluye categorías distintas cuando la fuente las identifica. Sus resultados no se suman a las cifras del campeonato.</p><HistoricalTable rows={outside} label="Fuera del campeonato mundial"/></section>:null}
  {honorary.length?<section id="titulo-honorifico" className="history-section"><h2>El título honorífico de Gran Premio de Europa</h2><p className="gp-lead">Esta distinción se añadía a una carrera nacional ya existente. Una misma prueba puede aparecer en la historia de su Gran Premio nacional y aquí como designación; no se cuenta dos veces como evento del calendario.</p><HistoricalTable rows={honorary} label="Designaciones honoríficas"/></section>:null}
  <section id="ediciones" className="history-section"><h2>Ediciones del Mundial</h2><p className="gp-lead">Cada año abre el artículo de la carrera, con clasificación, desarrollo del fin de semana y análisis disponible.</p><WorldTable rows={editions.world}/></section>
  <section id="telemetry" className="history-section gp-telemetry"><h2>La lectura de TelemetryOne</h2><strong>{modelEditions} de {editions.world.length}</strong><p>Ediciones con observaciones del modelo retrospectivo v7.6 en el archivo. El reporte de cada carrera incluye el análisis disponible de pilotos y autos, junto con resultados y fuentes. Los antecedentes anteriores al Mundial conservan su contexto histórico y no reciben estimaciones del modelo.</p><Link href="/ranking">Metodología y ranking de pilotos ↗</Link></section>
  <section id="palmares" className="history-section"><h2>Ganadores del Gran Premio en el Mundial</h2><div className="gp-palmares">{[{label:'Pilotos',items:drivers},{label:'Constructores',items:teams}].map(({label,items})=><div key={String(label)}><h3>{String(label)}</h3><ol>{items.map(item=><li key={item.id}><Link prefetch={false} href={item.href}>{item.name}</Link><strong>{item.wins}</strong><small>{editionYears(editions.world.filter(row=>label==='Pilotos'?row.winners.some(w=>w.id===item.id):row.constructors.some(t=>t.id===item.id)).map(row=>row.year))}</small></li>)}</ol></div>)}</div></section>
  <section id="fuentes" className="history-section history-sources"><h2>Fuentes y criterios</h2><ul>{article.sources.map(source=><li key={source.url}><a href={source.url} {...external}>{source.label} ↗</a></li>)}{editions.historicalSource?<li><a href={editions.historicalSource} {...external}>Tabla histórica y revisión consultada ↗</a></li>:null}<li><a href="https://github.com/f1db/f1db" {...external}>F1DB · resultados y coordenadas del Mundial · CC BY 4.0 ↗</a></li><li><a href={entity.sources.statsf1} {...external}>StatsF1 · contraste de resultados ↗</a></li></ul><p className="history-note">Texto de elaboración propia. Resultados mundialistas hasta {data.meta.through}; los antecedentes y las pruebas ajenas al campeonato están separados. Las cancelaciones y las filas sin ganador declarado no se cuentan como ediciones con ganador. El palmarés corresponde solo al Mundial y conserva los triunfos compartidos. Grilla P1 identifica al piloto que salió primero, que puede diferir del autor de la pole oficial por sanciones; su tiempo se muestra cuando está registrado. Un guion significa que falta un dato. Las crónicas históricas abren referencias externas cuando el archivo no contiene un reporte de esa época.</p><p className="history-note">Las fotografías y planos conservan sus créditos y licencias. Las imágenes de otra época se identifican en el pie y no se atribuyen a todas las ediciones. Las coordenadas remiten a F1DB o a la página de la sede, y los puntos de localidades se distinguen de las ubicaciones de circuitos.</p><Link href="/historia#metodologia">Criterios generales del archivo ↗</Link></section>
  <p className="history-note">Dibujos de referencia del archivo: <a href={LAYOUT_CREDIT.url} {...external}>{LAYOUT_CREDIT.label} ↗</a>.</p>
 </div><SiteFooter/></main>;
}
