import { Suspense } from "react";
import Link from "next/link";
import { HistoryCharts } from "./HistoryCharts";
import { historyCategories, type HistoryEntity } from "@/lib/history";
import { tidyNarrative } from "@/lib/text";
import { getWikipediaHistory } from "@/lib/wikipedia-history";

const number = (value: number) => value.toLocaleString("es-AR");

async function WikipediaContext({ entity }: { entity: HistoryEntity }) {
  const context = await getWikipediaHistory(entity.sources.wikipediaTitle);
  if (!context) return <div className="history-wikipedia"><h3>Contexto enciclopédico</h3><p>No pudimos verificar el artículo ahora. Podés consultar la búsqueda de Wikipedia; el archivo y los gráficos siguen disponibles.</p><a href={`https://en.wikipedia.org/wiki/Special:Search?search=${encodeURIComponent(entity.sources.wikipediaTitle)}`} target="_blank" rel="noreferrer">Buscar en Wikipedia ↗</a></div>;
  const founders = context.facts.filter(f => f.label === "Fundador").map(f => f.value);
  const headquarters = context.facts.find(f => f.label === "Sede");
  const birthplace = context.facts.find(f => f.label === "Lugar de nacimiento");
  return <div className="history-wikipedia">
    <p className="eyebrow eyebrow-red">WIKIPEDIA · WIKIDATA</p><h3>El contexto detrás de los resultados</h3>
    {founders.length ? <p>La documentación enciclopédica identifica a {founders.join(", ")} en la fundación de {entity.name}.{headquarters ? ` Su sede registrada es ${headquarters.value}.` : ""}</p> : birthplace ? <p>La ficha enciclopédica sitúa el nacimiento de {entity.name} en {birthplace.value}. Este contexto complementa el recorrido deportivo del archivo.</p> : <p>El artículo «{context.title}» amplía el contexto histórico de {entity.name}. Podés seguir sus capítulos junto al recorrido estadístico de esta ficha.</p>}
    {context.facts.length ? <dl className="history-facts">{context.facts.map((f, i) => <div key={`${f.label}/${i}`}><dt>{f.label}</dt><dd>{f.value}</dd></div>)}</dl> : null}
    <div className="history-reading">{context.sections.map(s => <a href={s.url} key={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>)}</div>
    <p className="history-note"><a href={context.revisionUrl ?? context.url} target="_blank" rel="noreferrer">Artículo y revisión consultada ↗</a>{context.wikidataUrl ? <> · <a href={context.wikidataUrl} target="_blank" rel="noreferrer">Datos estructurados (CC0) ↗</a></> : null}. Redacción propia a partir de hechos; los capítulos abren la fuente original.</p>
  </div>;
}

export function HistoryDossier({ entity }: { entity: HistoryEntity }) {
  const stats = entity.stats;
  const driver = entity.category === "drivers";
  const values = [["INSCRIPCIONES DE PILOTOS", stats.entries], ["GP DEL ARCHIVO", stats.races], ["PARTICIPACIONES EN CARRERA", stats.starts], ["VICTORIAS", stats.wins], ["PODIOS", stats.podiums], ["SALIDAS P1", stats.poles], ["VUELTAS RÁPIDAS", stats.fastestLaps], ["ABANDONOS REGISTRADOS", stats.retirements]] as const;
  return <article className="history-dossier">
    <nav className="history-profile-nav" aria-label="Secciones de la ficha"><a href="#historia">Historia</a><a href="#evolucion">Evolución</a><a href="#hitos">Hitos</a><a href="#conexiones">Conexiones</a><a href="#fuentes">Fuentes</a><Link href="/historia">Todo el archivo →</Link></nav>
    <section id="historia" className="history-section">
      <div className="detail-heading"><div><p className="eyebrow eyebrow-red">{entity.firstSeason}–{entity.lastSeason} · HISTORIA Y RESULTADOS</p><h2>UNA TRAYECTORIA, <em>EN CONTEXTO</em></h2></div></div>
      <div className="history-story">{entity.narrative.map((paragraph, i) => <p key={i}>{tidyNarrative(paragraph)}</p>)}</div>
      {entity.editorialSources?.length ? <p className="history-note">Referencias del relato · revisadas el {entity.editorialReviewedAt}: {entity.editorialSources.map((url, i) => <span key={url}>{i ? " · " : ""}<a href={url} target="_blank" rel="noreferrer">{new URL(url).hostname.includes("statsf1") ? "StatsF1" : `Wikipedia · ${decodeURIComponent(new URL(url).pathname.split("/wiki/")[1] ?? "").replaceAll("_", " ")}`} ↗</a></span>)}</p> : null}
      <p className="history-note">Síntesis original a partir de registros de F1DB y, donde existe cobertura, de la investigación de TelemetryOne. Corte del archivo: diciembre de 2025.</p>
      <div className="history-stat-grid">{values.map(([label, value]) => <div key={label}><span>{label}</span><strong>{number(value)}</strong></div>)}</div>
      <p className="history-note">Una inscripción puede terminar en DNS, DNQ o DNPQ; por eso inscripciones y participaciones difieren. Salidas P1 cuenta posiciones de salida, que pueden diferir de las poles oficiales. {driver ? "Los autos compartidos se cuentan una vez por piloto y GP." : "Victorias y podios de equipamiento se cuentan una vez por auto y carrera; en naciones se cuentan los logros de cada piloto."}</p>
      {driver ? <p className="history-note">Victorias por participación: {stats.starts ? (stats.wins / stats.starts * 100).toFixed(1) : "0.0"}%. Podios por participación: {stats.starts ? (stats.podiums / stats.starts * 100).toFixed(1) : "0.0"}%. {entity.officialPoints !== null ? `Puntos computados en standings de campeonato: ${entity.officialPoints.toLocaleString("es-AR")}, bajo los reglamentos de cada año.` : ""}</p> : null}
      <Suspense fallback={<div className="history-wikipedia"><h3>Contexto enciclopédico</h3><p>Consultando los hechos y capítulos de Wikipedia…</p><a href={entity.sources.wikipedia} target="_blank" rel="noreferrer">Abrir la referencia ↗</a></div>}><WikipediaContext entity={entity} /></Suspense>
    </section>
    <section id="evolucion" className="history-section"><div className="detail-heading"><div><p className="eyebrow eyebrow-red">ESTADÍSTICAS + INVESTIGACIÓN</p><h2>CÓMO CAMBIÓ <em>SU RENDIMIENTO</em></h2></div></div><HistoryCharts seasons={entity.seasons} ratings={entity.ratingHistory} />
      {entity.model?.model ? <div className="history-model-context"><h3>Resultados frente a expectativa</h3><p>Dentro de las {number(entity.model.races ?? 0)} carreras del modelo: <strong>{entity.model.model.observedWins ?? "—"} créditos de victoria observados</strong> y <strong>{entity.model.model.expectedWins ?? "—"} esperados</strong>. La diferencia del modelo es <strong>{entity.model.model.winsAboveExpected ?? "—"}</strong>.</p><p className="history-note">El modelo reparte el crédito de una victoria compartida entre pilotos. Este total puede diferir del palmarés, que cuenta una victoria para cada piloto. Se mantiene la cobertura v7.6; no se resta su expectativa al total de victorias del archivo.</p><Link className="history-source-link" href="/estadisticas/laboratorio">Explorar los modelos y comparar pilotos →</Link></div> : <p className="history-note">{driver ? "Este piloto tiene resultados históricos, pero no una estimación ELO en la versión del modelo incluida." : "Estas cifras describen resultados. La ficha de equipamiento no atribuye por sí sola cuánto rendimiento pertenece al piloto, al auto o al equipo."}</p>}
    </section>
    <section id="hitos" className="history-section"><div className="detail-heading"><div><p className="eyebrow eyebrow-red">CRONOLOGÍA</p><h2>LOS MOMENTOS <em>CLAVE</em></h2></div></div><ol className="history-timeline">{entity.milestones.map((milestone, i) => <li key={i}><strong>{milestone.season}</strong><div><b>{milestone.label}</b><span>{milestone.event}{milestone.date ? ` · ${milestone.date}` : ""}</span></div></li>)}</ol></section>
    <section id="conexiones" className="history-section"><div className="detail-heading"><div><p className="eyebrow eyebrow-red">UN ARCHIVO CONECTADO</p><h2>NADIE CORRE <em>SOLO</em></h2></div></div>
      {entity.raceResults?.length ? <details><summary>Resultados históricos completos · {entity.raceResults.length} registros</summary><p className="history-note">Clasificaciones de F1DB. Los registros de autos compartidos se conservan; las estadísticas agregadas se deduplican. DNF: abandono; DNS: no largó; DNQ/DNPQ: no clasificó; DSQ: descalificado; NC: no clasificado.</p><div className="history-table-scroll history-rating-data"><table><thead><tr><th>Año</th><th>Gran Premio</th><th>Constructor</th><th>Motor</th><th>Grilla</th><th>Resultado</th><th>Vueltas</th><th>Puntos de carrera</th><th>Estado</th></tr></thead><tbody>{entity.raceResults.map((r, i) => <tr key={`${r.season}/${r.round}/${i}`}><td>{r.season}</td><td><Link prefetch={false} href={`/historia/carreras/${r.season}/${r.round}`}>{r.event}</Link></td><td><Link prefetch={false} href={`/historia/constructors/${r.constructorId}`}>{r.constructorId}</Link></td><td>{r.engineId ? <Link prefetch={false} href={`/historia/engines/${r.engineId}`}>{r.engineId}</Link> : "—"}</td><td>{r.grid ?? "—"}</td><td>{r.position ?? r.status}{r.shared ? " · compartido" : ""}</td><td>{r.laps ?? "—"}</td><td>{r.points}</td><td>{r.retired ?? (r.fastest ? "Vuelta rápida" : "—")}</td></tr>)}</tbody></table></div></details> : null}
      <div className="history-connections">{entity.relations.map(group => <details key={group.category} open={group.category === "constructors" || (entity.category === "constructors" && group.category === "engines")}><summary>{historyCategories[group.category]} <span>{group.items.length}</span></summary><div className="history-table-scroll"><table><thead><tr><th>Nombre</th><th>Etapa</th><th>GP compartidos</th><th>Victorias conjuntas</th></tr></thead><tbody>{group.items.map(item => <tr key={item.id}><td><Link prefetch={false} href={item.href}>{item.name} →</Link></td><td>{item.firstSeason}–{item.lastSeason}</td><td>{item.races}</td><td>{item.wins}</td></tr>)}</tbody></table></div></details>)}</div>
      {entity.model?.teammates?.length ? <details className="history-teammates"><summary>Comparación con compañeros · muestra elegible del modelo</summary><p className="history-note">Sólo carreras elegibles para rating en v7.6; puede excluir abandonos mecánicos. «Delante» es un conteo dentro de esas carreras.</p><div className="history-table-scroll"><table><thead><tr><th>Compañero</th><th>GP elegibles</th><th>Delante en carrera</th><th>Delante en clasificación</th><th>Ventaja ELO media</th></tr></thead><tbody>{entity.model.teammates.map(m => <tr key={m.id}><td><Link prefetch={false} href={`/pilotos/${m.id}`}>{m.name} →</Link></td><td>{m.races}</td><td>{m.finishWins}</td><td>{m.qualifyingWins}</td><td>{m.averageRatingEdge > 0 ? "+" : ""}{m.averageRatingEdge}</td></tr>)}</tbody></table></div></details> : null}
      {entity.engineSpecs?.length ? <details><summary>Catálogo técnico de motores · {entity.engineSpecs.length} variantes</summary><p className="history-note">Catálogo de F1DB. La lista de variantes no implica que todas estén cubiertas por las temporadas mostradas.</p><div className="history-table-scroll"><table><thead><tr><th>Motor</th><th>Litros</th><th>Configuración</th><th>Aspiración</th></tr></thead><tbody>{entity.engineSpecs.map(e => <tr key={String(e.id)}><td>{e.fullName}</td><td>{e.capacity ?? "—"}</td><td>{e.configuration ?? "—"}</td><td>{e.aspiration ?? "—"}</td></tr>)}</tbody></table></div></details> : null}
      {entity.biography.layouts?.length ? <details><summary>Configuraciones históricas del circuito</summary><div className="history-table-scroll"><table><thead><tr><th>Configuración</th><th>Longitud</th><th>Curvas</th></tr></thead><tbody>{entity.biography.layouts.map(l => <tr key={l.id}><td>{l.id}</td><td>{l.length} km</td><td>{l.turns}</td></tr>)}</tbody></table></div></details> : null}
    </section>
    <section id="fuentes" className="history-section history-sources"><p className="eyebrow eyebrow-red">PROCEDENCIA</p><h3>Seguí cada dato hasta su fuente</h3>
      <dl><div><dt>Resultados y hechos de identidad</dt><dd><a target="_blank" rel="noreferrer" href="https://github.com/f1db/f1db">F1DB · CC BY 4.0 ↗</a>. Agregación propia de clasificaciones y standings, 1950–2025.</dd></div><div><dt>Referencia estadística para contrastar</dt><dd><a target="_blank" rel="noreferrer" href={entity.sources.statsf1}>StatsF1 ↗</a>. Consulta complementaria; sus biografías y su base completa no se reproducen aquí.</dd></div><div><dt>Contexto enciclopédico</dt><dd><a target="_blank" rel="noreferrer" href={entity.sources.wikipedia}>Wikipedia ↗</a> y Wikidata. Hechos estructurados, enlaces a capítulos y revisión consultada cuando la fuente está disponible.</dd></div><div><dt>Investigación propia</dt><dd><Link href="/estadisticas/laboratorio">TelemetryOne v7.6 →</Link>. 1.138 eventos; estimaciones retrospectivas, con cobertura diferente del archivo de resultados.</dd></div></dl>
      <p className="history-note">El archivo incluye las 500 Millas de Indianápolis de 1950–1960 como pruebas del Campeonato Mundial. Las inscripciones cuentan registros presentes en las clasificaciones de F1DB; intentos o retiros previos sin registro pueden faltar. Los nombres históricos de constructores y motores conservan identidades separadas. Los puntos de campeonato respetan las reglas de cada temporada; no equivalen a una escala moderna uniforme. En neumáticos y circuitos, un resultado conjunto no demuestra una contribución causal.</p>
      <Link className="history-source-link" href="/historia#metodologia">Cobertura, metodología y limitaciones →</Link>
    </section>
  </article>;
}
