import Link from "next/link";
import { SiteHeader } from "./SiteHeader";
import { SiteFooter } from "./SiteFooter";
import { ArchiveReference } from "./ArchiveReference";
import { ArchiveMediaFigure } from "./ArchiveMediaFigure";
import { Encyclopedia, EncyclopediaSection } from "./Encyclopedia";
import { RaceModelAnalysis } from "./RaceModelAnalysis";
import type { ArchiveRef, Championship, HistoricRace, SessionRow, StandingRow } from "@/lib/championship-history";
import { tidyNarrative } from "@/lib/text";
import { dateLabel, number, resultColor } from "@/lib/weekend-format";

function SessionTable({ rows, label, qualifying = false, grid = false }: { rows: SessionRow[]; label: string; qualifying?: boolean; grid?: boolean }) {
  if (!rows.length) return <p className="ency-note">No hay registros de esta sesión en el archivo.</p>;
  const multiQ = qualifying && rows.some(r => r.q1 || r.q2 || r.q3);
  return <div className="ency-table-scroll"><table><caption>{label}</caption><thead><tr><th>Pos.</th><th>Nº</th><th>Piloto</th><th>Constructor / motor</th>{multiQ ? <><th>Q1</th><th>Q2</th><th>Q3</th></> : <th>{qualifying || grid ? "Tiempo" : "Tiempo / diferencia"}</th>}{!qualifying && !grid ? <><th>Vueltas</th><th>Grilla</th><th>Puntos</th><th>Estado / notas</th></> : null}</tr></thead><tbody>{rows.map((r, i) => <tr key={`${r.driver.id}/${r.number}/${i}`}><td className={qualifying || grid ? undefined : resultColor(r.position, r.reasonRetired)}>{r.position ?? "—"}</td><td>{r.number ?? "—"}</td><th scope="row"><ArchiveReference entity={r.driver} />{r.sharedCar ? <small>Conducción compartida</small> : null}</th><td><ArchiveReference entity={r.constructor} /><small><ArchiveReference entity={r.engine} /></small></td>{multiQ ? <><td>{r.q1 ?? "—"}</td><td>{r.q2 ?? "—"}</td><td>{r.q3 ?? "—"}</td></> : <td>{r.gap ?? r.time ?? "—"}</td>}{!qualifying && !grid ? <><td>{r.laps ?? "—"}</td><td>{r.gridPosition ?? "—"}</td><td>{number(r.points, 2)}</td><td>{r.reasonRetired ?? (typeof r.position === "number" ? "Clasificado" : r.position ?? "—")}{r.timePenalty ? <small>Penalización: {r.timePenalty}</small> : null}</td></> : null}</tr>)}</tbody></table></div>;
}
function Standings({ rows, label }: { rows: StandingRow[]; label: string }) {
  return rows.length ? <div className="ency-table-scroll"><table><caption>{label}</caption><thead><tr><th>Pos.</th><th>{label}</th><th>Puntos</th></tr></thead><tbody>{rows.map((r, i) => <tr key={`${r.entity.id}/${r.engine?.id}/${i}`}><td>{r.position ?? "—"}</td><th scope="row"><ArchiveReference entity={r.entity} />{r.engine ? <small><ArchiveReference entity={r.engine} /></small> : null}</th><td>{number(r.points, 2)}</td></tr>)}</tbody></table></div> : <p className="ency-note">Sin clasificación de {label.toLowerCase()} en esta prueba.</p>;
}
export function RaceDossier({ race, season, cars }: { race: HistoricRace; season: Championship; cars: ArchiveRef[] }) {
  const { year, round } = race;
  const index = season.races.findIndex(r => r.round === round), previous = season.races[index - 1], next = season.races[index + 1];
  const sprint = race.sessions.sprint.length > 0;
  const sections = [{ id: "resumen", name: "Resumen y antecedentes" }, { id: "circuito", name: "Circuito y distancia" }, { id: "clasificacion", name: "Clasificación" }, { id: "parrilla", name: "Parrilla de salida" }, ...(sprint ? [{ id: "sprint", name: "Fin de semana sprint" }] : []), { id: "carrera", name: "Carrera y resultados" }, { id: "vueltas", name: "Vueltas rápidas y boxes" }, { id: "campeonato", name: "Campeonato después del GP" }, { id: "modelo", name: "Análisis TelemetryOne" }, { id: "referencias", name: "Notas y fuentes" }];
  const aside = <><div className="ency-infobox"><p className="infobox-kicker">RONDA {round} / {season.races.length}</p><h2>{race.eventName}</h2><p className="infobox-subtitle">{year} · {dateLabel(race.date)}</p>{race.poster ? <ArchiveMediaFigure media={race.poster} alt={`Póster del ${race.eventName} de ${year}`} /> : <p className="poster-pending">Póster histórico por documentar</p>}<dl><div><dt>Circuito</dt><dd><ArchiveReference entity={race.circuit} /></dd></div><div><dt>Longitud</dt><dd>{number(race.facts.courseLength, 3)} km</dd></div><div><dt>Vueltas / distancia</dt><dd>{race.facts.laps ?? "—"} / {number(race.facts.distance, 3)} km</dd></div><div><dt>Pole position</dt><dd><ArchiveReference entity={race.pole?.driver} /><small>{race.pole?.time}</small></dd></div><div><dt>Vuelta rápida</dt><dd>{race.fastest.map(f => <div key={f.driver.id}><ArchiveReference entity={f.driver} /><small>{f.time}{f.lap ? ` · vuelta ${f.lap}` : ""}</small></div>)}</dd></div></dl><h3>Podio</h3><ol className="infobox-podium">{race.podium.map((p, i) => <li key={`${p.driver.id}/${i}`}><b>{p.position}</b><span><ArchiveReference entity={p.driver} /><small><ArchiveReference entity={p.constructor} /></small></span></li>)}</ol><div className="infobox-model"><b>TELEMETRY ONE / v7.6</b><p>{race.model.length ? `${race.model.length} observaciones · análisis retrospectivo` : "Sin observaciones del modelo"}</p></div></div><Link className="ency-aside-link" href={`/historia/seasons/${year}`}>Ver la temporada {year} →</Link></>;
  return <main id="top" className="ency-page"><SiteHeader /><div className="ency-page-wrap"><header className="ency-title"><nav className="ency-breadcrumb" aria-label="Ruta del artículo"><Link href="/historia">Historia</Link><span>/</span><Link href={`/historia/seasons/${year}`}>Temporada {year}</Link><span>/</span><span>Ronda {round}</span></nav><div className="ency-title-row"><div><p className="ency-eyebrow">GRAN PREMIO · RONDA {String(round).padStart(2, "0")}</p><h1>{race.eventName} de {year}</h1><p className="ency-subtitle">{dateLabel(race.date)} · {race.circuit.name} · resultados y análisis de carrera</p></div><nav className="ency-neighbors" aria-label="Carreras contiguas">{previous ? <Link href={previous.href}>← R{previous.round}</Link> : null}{next ? <Link href={next.href}>R{next.round} →</Link> : null}</nav></div></header><Encyclopedia sections={sections} aside={aside}>
    <EncyclopediaSection id="resumen" title="Resumen y antecedentes" kicker="HISTORIA" open>{race.narrative.map(p => <p key={p}>{tidyNarrative(p)}</p>)}{race.editorial ? <><p>{race.editorial.text}</p><p className="ency-note">Contexto contrastado con <a href={race.editorial.url} target="_blank" rel="noreferrer">Wikipedia ↗</a>; redacción propia.</p></> : <p>El relato y los antecedentes de esta carrera se pueden ampliar en <a href={race.sources.wikipedia} target="_blank" rel="noreferrer">Wikipedia ↗</a>.</p>}<div className="ency-champion-strip">{race.podium.filter(p => p.position === 1).map(p => <div key={p.driver.id}><small>GANADOR</small><strong><ArchiveReference entity={p.driver} /></strong><span>{p.time ?? "Victoria compartida"}</span></div>)}<div><small>POLE POSITION</small><strong><ArchiveReference entity={race.pole?.driver} /></strong><span>{race.pole?.time ?? "Tiempo no registrado"}</span></div></div></EncyclopediaSection>
    <EncyclopediaSection id="circuito" title="Circuito y distancia" kicker="ESCENARIO"><dl className="ency-facts-grid"><div><dt>Nombre oficial</dt><dd>{race.facts.officialName ?? race.name}</dd></div><div><dt>Circuito</dt><dd><ArchiveReference entity={race.circuit} /></dd></div><div><dt>Configuración histórica</dt><dd>{race.facts.circuitLayoutId ?? "—"}</dd></div><div><dt>Longitud por vuelta</dt><dd>{number(race.facts.courseLength, 3)} km</dd></div><div><dt>Vueltas de carrera</dt><dd>{race.facts.laps ?? "—"}</dd></div><div><dt>Distancia oficial</dt><dd>{number(race.facts.distance, 3)} km</dd></div><div><dt>Curvas</dt><dd>{race.facts.turns ?? "—"}</dd></div><div><dt>Formato de clasificación</dt><dd>{race.facts.qualifyingFormat?.replaceAll("_", " ") ?? "—"}</dd></div></dl></EncyclopediaSection>
    <EncyclopediaSection id="clasificacion" title="Clasificación" kicker="SESIONES"><SessionTable rows={race.sessions.qualifying} label="Resultados de clasificación" qualifying /><p className="ency-note">Los tiempos corresponden al formato de la época. La pole oficial puede diferir del primer lugar de la parrilla tras penalizaciones; en los sprint de 2021 se otorgó al ganador del sprint.</p></EncyclopediaSection>
    <EncyclopediaSection id="parrilla" title="Parrilla de salida" kicker="ANTES DE LA LARGADA"><SessionTable rows={race.sessions.grid} label="Parrilla oficial" grid /></EncyclopediaSection>
    {sprint ? <EncyclopediaSection id="sprint" title="Fin de semana sprint" kicker="SESIONES ADICIONALES"><h3>Clasificación sprint</h3><SessionTable rows={race.sessions.sprintQualifying} label="Clasificación sprint" qualifying /><h3>Resultado sprint</h3><SessionTable rows={race.sessions.sprint} label="Resultado sprint" /></EncyclopediaSection> : null}
    <EncyclopediaSection id="carrera" title="Carrera y resultados" kicker="CLASIFICACIÓN OFICIAL" open><SessionTable rows={race.sessions.race} label="Clasificación del Gran Premio" /><p className="ency-note">Los puntos son los de esta carrera. Los abandonos conservan su posición oficial cuando está registrada. La conducción compartida se muestra por piloto con el puntaje asignado a cada uno.</p></EncyclopediaSection>
    <EncyclopediaSection id="vueltas" title="Vueltas rápidas y paradas en boxes" kicker="DETALLE DE CARRERA"><h3>Vueltas rápidas registradas</h3><div className="ency-table-scroll"><table><thead><tr><th>Pos.</th><th>Piloto</th><th>Constructor</th><th>Tiempo</th><th>Vuelta</th></tr></thead><tbody>{race.sessions.fastestLaps.map((r, i) => <tr key={`${r.driver.id}/${i}`}><td>{r.position ?? "—"}</td><th><ArchiveReference entity={r.driver} /></th><td><ArchiveReference entity={r.constructor} /></td><td>{r.time ?? "—"}</td><td>{r.lap ?? "—"}</td></tr>)}</tbody></table></div>{race.pitStops?.length ? <><h3>Paradas en boxes</h3><div className="ency-table-scroll"><table><thead><tr><th>Piloto</th><th>Parada</th><th>Vuelta</th><th>Hora</th><th>Duración</th></tr></thead><tbody>{race.pitStops.map((p, i) => <tr key={i}><th><ArchiveReference entity={p.driver} /></th><td>{p.stop ?? "—"}</td><td>{p.lap}</td><td>{p.time ?? "—"}</td><td>{p.duration ?? "—"}</td></tr>)}</tbody></table></div></> : <p className="ency-note">El archivo no contiene un registro de paradas en boxes para esta carrera.</p>}</EncyclopediaSection>
    <EncyclopediaSection id="campeonato" title="Campeonato después del Gran Premio" kicker="PUNTOS OFICIALES"><p>Situación del campeonato al finalizar esta ronda, aplicando el reglamento de {year}.</p><div className="race-standings-grid"><Standings rows={race.standings.drivers} label="Pilotos" /><Standings rows={race.standings.constructors} label="Constructores" /></div><p className="ency-note">{season.scoring.text}</p></EncyclopediaSection>
    <EncyclopediaSection id="modelo" title="Análisis TelemetryOne" kicker="INVESTIGACIÓN PROPIA"><RaceModelAnalysis rows={race.model} cars={cars} download={race.modelExport} /></EncyclopediaSection>
    <EncyclopediaSection id="referencias" title="Notas y fuentes" kicker="REFERENCIAS"><ul className="ency-sources"><li><a href={race.sources.f1db} target="_blank" rel="noreferrer">F1DB · CC BY 4.0</a>: resultados, tiempos, inscripciones y standings. Revisión {season.sources.f1dbRevision.slice(0, 12)}.</li><li><a href={race.sources.wikipedia} target="_blank" rel="noreferrer">Wikipedia · {race.name}</a>: contexto y estructura del artículo.</li><li><a href={`https://www.statsf1.com/es/${year}.aspx`} target="_blank" rel="noreferrer">StatsF1 · temporada {year}</a>: referencia estadística.</li><li>TelemetryOne v7.6: <code>{race.sources.model}</code>. Todas las columnas originales se conservan en la descarga por carrera.</li></ul><p className="ency-note">Las condiciones meteorológicas que aparecen en el análisis son entradas o aproximaciones del modelo. Los resultados y las estimaciones usan conjuntos con coberturas distintas. Sólo se incorporan pósters históricos con una fuente y una licencia documentadas.</p><a href={`/history/races/${race.id}.json`} target="_blank" rel="noreferrer">Datos de este Gran Premio (JSON) ↗</a></EncyclopediaSection>
  </Encyclopedia></div><SiteFooter /></main>;
}
