import Link from "next/link";
import { SiteHeader } from "./SiteHeader";
import { SiteFooter } from "./SiteFooter";
import { ArchiveReference } from "./ArchiveReference";
import { Encyclopedia, EncyclopediaSection } from "./Encyclopedia";
import { SeasonBalance } from "./SeasonBalance";
import { SeasonStatistics } from "./SeasonStatistics";
import { SeasonSimulator } from "./SeasonSimulator";
import { simulationInput } from "@/lib/season-simulation";
import { SeasonModelChart } from "./SeasonModelChart";
import { ArchiveMediaFigure } from "./ArchiveMediaFigure";
import { DriverPortrait, TeamMark } from "./ArchiveImages";
import type { CarSummary, Championship } from "@/lib/championship-history";
import { tidyNarrative } from "@/lib/text";
import { dateLabel, number, percent } from "@/lib/weekend-format";

const sections = [
  { id: "panorama", name: "Resumen de la temporada" }, { id: "participantes", name: "Equipos y pilotos" },
  { id: "calendario", name: "Calendario y carreras" }, { id: "reglamento", name: "Reglamento y cambios" },
  { id: "resultados", name: "Resultados y campeonatos" }, { id: "simulacion", name: "Con los puntos actuales" },
  { id: "estadisticas", name: "Balance estadístico" },
  { id: "evolucion", name: "Evolución del campeonato" }, { id: "autos", name: "Modelos de auto" },
  { id: "investigacion", name: "Análisis TelemetryOne" }, { id: "fuentes", name: "Notas y fuentes" },
];
export function SeasonDossier({ season, sprints, cars }: { season: Championship; sprints: Parameters<typeof simulationInput>[1]; cars: CarSummary[] }) {
  const { year, races } = season;
  const champion = season.driverStandings.find(s => s.position === 1);
  const team = season.constructorStandings.find(s => s.position === 1);
  const modelEvents = races.filter(r => r.modelCount).length;
  const aside = <><div className="ency-infobox"><dl><div><dt>Grandes Premios</dt><dd>{races.length}</dd></div><div><dt>Primera carrera</dt><dd><Link href={races[0].href}>{dateLabel(races[0].date)}</Link></dd></div><div><dt>Última carrera</dt><dd><Link href={races.at(-1)!.href}>{dateLabel(races.at(-1)!.date)}</Link></dd></div><div><dt>Campeón de pilotos</dt><dd className="infobox-figure"><DriverPortrait id={champion?.entity.id} name={champion?.entity.name ?? ""} /><span><ArchiveReference entity={champion?.entity} /><small>{number(champion?.points, 2)} puntos</small></span></dd></div><div><dt>Campeón de constructores</dt><dd className="infobox-figure">{team ? <><TeamMark id={team.entity.id} name={team.entity.name} /><span><ArchiveReference entity={team.entity} /><small>{number(team.points, 2)} puntos</small></span></> : "Campeonato no disputado"}</dd></div><div><dt>Pilotos inscritos</dt><dd>{season.driverStandings.length}</dd></div><div><dt>Modelos inscritos</dt><dd>{season.cars.length}</dd></div></dl><div className="infobox-model"><b>TELEMETRY ONE / v7.6</b><p>{modelEvents}/{races.length} carreras · {season.model.length} pilotos</p></div></div><p className="ency-aside-note">Resultados hasta 2025. Incluye Indianápolis entre 1950 y 1960. Todas las carreras abren su propia ficha.</p></>;
  return <main id="top" className="ency-page"><SiteHeader /><div className="ency-page-wrap"><header className="ency-title"><nav className="ency-breadcrumb" aria-label="Ruta del artículo"><Link href="/historia">Estadísticas</Link><span>/</span><Link href="/historia#temporadas">Temporadas</Link></nav><div className="ency-title-row"><div><h1>Temporada {year}</h1><p className="ency-subtitle">{races.length} Grandes Premios, del {dateLabel(races[0].date)} al {dateLabel(races.at(-1)!.date)}</p></div><nav className="ency-neighbors" aria-label="Temporadas contiguas">{year > 1950 ? <Link href={`/historia/seasons/${year - 1}`}>← {year - 1}</Link> : null}{year < 2025 ? <Link href={`/historia/seasons/${year + 1}`}>{year + 1} →</Link> : null}</nav></div></header><Encyclopedia sections={sections} aside={aside}>
    <EncyclopediaSection id="panorama" title="Resumen de la temporada" kicker="01 / HISTORIA" open>{season.narrative.map(p => <p key={p}>{tidyNarrative(p)}</p>)}{season.editorial ? <><p>{season.editorial.text}</p><p className="ency-note">Contexto contrastado con <a href={season.editorial.url} target="_blank" rel="noreferrer">Wikipedia ↗</a>; redacción propia.</p></> : null}</EncyclopediaSection>
    <EncyclopediaSection id="participantes" title="Equipos y pilotos" kicker="02 / PARTICIPANTES"><p>Inscripciones del campeonato, con los chasis y motores declarados. Una fila puede cubrir varios modelos usados durante el año; no implica que todos hayan largado cada ronda.</p><div className="ency-table-scroll"><table><caption>Todos los pilotos, chasis y motores de {year}</caption><thead><tr><th>Escudería / constructor</th><th>Piloto</th><th>Chasis</th><th>Motor</th><th>Neumáticos</th><th>Rondas</th><th>Mejor resultado</th><th>Mejor salida</th></tr></thead><tbody>{season.entrants.map((e, i) => <tr key={i}><td><strong>{e.entrant}</strong><small><ArchiveReference entity={e.constructor} /></small></td><th scope="row"><ArchiveReference entity={e.driver} /></th><td>{e.cars.length ? e.cars.map(c => <small key={c.id}><ArchiveReference entity={c} /></small>) : e.chassis.join(" / ") || "Modelo no identificado"}</td><td><ArchiveReference entity={e.engine} /><small>{e.engineModelName}</small></td><td><ArchiveReference entity={e.tyre} /></td><td>{e.rounds}</td><td>{e.bestFinish ?? "—"}</td><td>{e.bestGrid ?? "—"}</td></tr>)}</tbody></table></div></EncyclopediaSection>
    <EncyclopediaSection id="calendario" title="Calendario y carreras" kicker="03 / GRANDES PREMIOS" open><p>Cada Gran Premio abre su ficha con resultados y el análisis ELO v7.6.</p><div className="ency-table-scroll"><table className="season-calendar"><caption>Calendario del Campeonato Mundial {year}</caption><thead><tr><th>R.</th><th>Fecha</th><th>Gran Premio / circuito</th><th>Ganador</th><th>Pole</th><th>Vuelta rápida</th></tr></thead><tbody>{races.map(r => <tr key={r.id}><td><Link href={r.href} prefetch={false}>{String(r.round).padStart(2, "0")}</Link></td><td>{dateLabel(r.date)}</td><th scope="row"><Link href={r.href} prefetch={false}>{r.eventName} →</Link><small><ArchiveReference entity={r.circuit} /></small></th><td>{r.podium.filter(p => p.position === 1).map(p => <small key={p.driver.id}><ArchiveReference entity={p.driver} /></small>)}</td><td><ArchiveReference entity={r.pole} /></td><td>{r.fastest.map(f => <small key={f.id}><ArchiveReference entity={f} /></small>)}</td></tr>)}</tbody></table></div></EncyclopediaSection>
    <EncyclopediaSection id="reglamento" title="Reglamento y cambios" kicker="04 / CONTEXTO"><h3>Puntuación del campeonato</h3><p>{season.scoring.text}</p><a href={season.scoring.url} target="_blank" rel="noreferrer">Reglas y sistema de puntuación en Wikipedia ↗</a>{season.changes ? <><h3>Cambios respecto de {year - 1}</h3><p>Comparación de las inscripciones y el calendario con el año anterior. La incorporación de una identidad no implica que su organización haya sido creada ese año.</p><dl className="ency-change-list">{([['Pilotos incorporados', season.changes.drivers], ['Constructores incorporados', season.changes.constructors], ['Circuitos incorporados', season.changes.circuits]] as const).map(([label, refs]) => <div key={label}><dt>{label}</dt><dd>{refs.length ? refs.map((r, i) => <span key={r.id}>{i ? ", " : ""}<ArchiveReference entity={r} /></span>) : "Sin incorporaciones registradas"}</dd></div>)}</dl></> : null}<h3>Reglamento técnico y deportivo</h3><p>La clasificación conserva las reglas de su época, incluidas pruebas con puntos reducidos, conducción compartida, descartes y sprint. Los cambios reglamentarios y sus antecedentes se pueden ampliar en el artículo de esta temporada.</p><a href={season.sources.wikipedia} target="_blank" rel="noreferrer">Historia y cambios reglamentarios de {year} en Wikipedia ↗</a></EncyclopediaSection>
    <EncyclopediaSection id="resultados" title="Resultados y campeonatos" kicker="05 / BALANCE" open><p>{season.scoring.text}</p><SeasonBalance year={year} races={races} driverStandings={season.driverStandings} constructorStandings={season.constructorStandings} driverResults={season.driverResults} qualifyingResults={season.qualifyingResults} gridResults={season.gridResults} /></EncyclopediaSection>
    <EncyclopediaSection id="simulacion" title="Con los puntos actuales" kicker="06 / SIMULACIÓN"><SeasonSimulator input={simulationInput(season, sprints)} /></EncyclopediaSection>
    <EncyclopediaSection id="estadisticas" title="Balance estadístico" kicker="07 / STATS"><SeasonStatistics stats={season.stats} coverage={season.statCoverage} year={year} /></EncyclopediaSection>
    <EncyclopediaSection id="evolucion" title="Evolución del campeonato" kicker="08 / GRÁFICOS"><SeasonModelChart model={season.model} races={races} standings={season.driverStandings} /></EncyclopediaSection>
    <EncyclopediaSection id="autos" title="Modelos de auto" kicker="09 / CHASIS"><p>Catálogo de modelos declarados para la temporada. Las fotos están asociadas al modelo identificado y conservan su autor y licencia.</p><Link href={`/historia/autos?season=${year}`}>Explorar el índice de autos de {year} →</Link><div className="season-car-grid">{cars.map(car => <div className="season-car" key={car.id}>{car.photo ? <ArchiveMediaFigure media={car.photo} alt={car.name} /> : <div className="car-no-photo"><span>CHASIS</span><strong>{car.name}</strong><small>Fotografía por documentar</small></div>}<h3><Link href={car.href} prefetch={false}>{car.name} →</Link></h3><p>{car.engines.map((e, i) => <span key={e.id}>{i ? " / " : ""}<ArchiveReference entity={e} /></span>)}</p></div>)}</div></EncyclopediaSection>
    <EncyclopediaSection id="investigacion" title="Análisis TelemetryOne" kicker="10 / MODELO v7.6"><p>{modelEvents} de las {races.length} pruebas tienen observaciones del modelo. Las victorias observadas de esta tabla usan el crédito fraccionado de la investigación en autos compartidos; por eso pueden diferir del balance histórico de pilotos.</p><p>XW suma probabilidades de victoria del piloto. XP expresa rendimiento esperado entre 0 y 1. El ELO mostrado es retrospectivo y no debe interpretarse como un pronóstico calculado sólo con información previa a la carrera.</p><div className="ency-table-scroll"><table><caption>Resumen del modelo en {year}</caption><thead><tr><th>Piloto</th><th>GP del modelo</th><th>Victorias observadas</th><th>Victorias esperadas XW</th><th>Balance V − XW</th><th>XP medio</th><th>ELO inicial</th><th>ELO final</th></tr></thead><tbody>{season.model.map(m => <tr key={m.driver.id}><th scope="row"><ArchiveReference entity={m.driver} /></th><td>{m.events}</td><td>{number(m.observedWins, 2)}</td><td>{number(m.expectedWins, 2)}</td><td>{number(m.observedWins - m.expectedWins, 2)}</td><td>{percent(m.meanXp)}</td><td>{number(m.firstElo, 1)}</td><td>{number(m.lastElo, 1)}</td></tr>)}</tbody></table></div><p>En cada ficha de carrera se pueden consultar ELO, XW, XP, expectativa del auto, descomposición piloto–auto–equipo y calidad de los datos, además de descargar todas las columnas originales de esa prueba.</p><Link href="/ranking">Abrir el ranking de TelemetryOne →</Link></EncyclopediaSection>
    <EncyclopediaSection id="fuentes" title="Notas y fuentes" kicker="11 / REFERENCIAS"><ul className="ency-sources"><li><a href="https://github.com/f1db/f1db" target="_blank" rel="noreferrer">F1DB · CC BY 4.0</a>: inscripciones, resultados y standings. Revisión {season.sources.f1dbRevision.slice(0, 12)}.</li><li><a href={season.sources.wikipedia} target="_blank" rel="noreferrer">Wikipedia · temporada {year}</a>: estructura enciclopédica y contexto; la redacción aquí es propia.</li><li><a href={`https://www.statsf1.com/es/${year}/bilan.aspx`} target="_blank" rel="noreferrer">StatsF1 · balance {year}</a>: referencia del balance y fuente atribuida de vueltas en cabeza donde se pudo verificar.</li><li>TelemetryOne v7.6: modelo retrospectivo, con cobertura propia. Sus estimaciones se mantienen separadas de los resultados oficiales.</li></ul><p className="ency-note">Se incluyen resultados hasta {season.sources.resultsThrough}. Las estadísticas lideradas pendientes y las fotos sin documentar están señaladas; no se completan con estimaciones. El catálogo de chasis identifica inscripciones de temporada, no una asignación exacta a cada carrera.</p><a href={`/history/championships/${year}.json`} target="_blank" rel="noreferrer">Consultar los datos de esta temporada (JSON) ↗</a></EncyclopediaSection>
  </Encyclopedia></div><SiteFooter /></main>;
}
