import Link from 'next/link';
import { SiteHeader } from './SiteHeader';
import { SiteFooter } from './SiteFooter';
import { Encyclopedia, EncyclopediaSection } from './Encyclopedia';
import { TyreBrand } from './TyreBrand';
import { TyrePerformance } from './TyrePerformance';
import { TyreTechnology } from './TyreTechnology';
import type { HistoryEntity } from '@/lib/history';
import { tyreCompanies, type TyreAnalysis } from '@/lib/tyre-history';
import { number, dateLabel, percent } from '@/lib/weekend-format';

const sections = [
  { id: 'fabricante', name: 'El fabricante' }, { id: 'historia', name: 'Historia y geografía' },
  { id: 'estadisticas', name: 'Estadísticas y competencia' }, { id: 'tecnologia', name: 'Materiales y propiedades' },
  { id: 'conexiones', name: 'Pilotos, equipos y motores' }, { id: 'hitos', name: 'Hitos del archivo' },
  { id: 'fuentes', name: 'Fuentes y metodología' }
];
function periods(years: number[]) {
  const groups: number[][] = [];
  for (const year of years) {
    const group = groups.at(-1);
    if (!group || year !== group.at(-1)! + 1) groups.push([year]); else group.push(year);
  }
  return groups.map(g => g.length === 1 ? String(g[0]) : `${g[0]}–${g.at(-1)}`).join(' · ');
}
export function TyreDossier({ entity, analysis }: { entity: HistoryEntity; analysis: TyreAnalysis }) {
  const company = tyreCompanies[entity.id];
  const relations = (category: string) => entity.relations.find(r => r.category === category)?.items ?? [];
  const stats = entity.stats;
  const brands = Object.entries(tyreCompanies).map(([id, c]) => ({ id, name: c.name })).sort((a, b) => a.name.localeCompare(b.name));
  const metrics = [
    ['Grandes Premios con registros', stats.races], ['Victorias', stats.wins], ['Pole positions registradas', analysis.officialPoles], ['Podios', stats.podiums],
    ['Vueltas rápidas', stats.fastestLaps], ['Temporadas', stats.seasons], ['Pilotos con inscripción', stats.drivers], ['Constructores', relations('constructors').length],
    ['Motoristas', relations('engines').length], ['Vueltas recorridas registradas', stats.laps], ['Inscripciones de pilotos', stats.entries], ['Participaciones de pilotos', stats.starts]
  ] as const;
  const aside = <><div className="ency-infobox"><p className="infobox-kicker">NEUMÁTICOS · {company.country}</p><h2>{company.name}</h2><TyreBrand company={company} /><dl><div><dt>Fundación</dt><dd>{company.founded}</dd></div><div><dt>{company.locationLabel}</dt><dd>{company.location}</dd></div><div><dt>Presencia en el archivo</dt><dd>{periods(entity.seasons.map(s => s.season))}</dd></div><div><dt>Mejor resultado / salida</dt><dd>{analysis.bestFinish ?? '—'} / {analysis.bestGrid ?? '—'}</dd></div><div><dt>Último GP registrado</dt><dd><Link href={analysis.last.href}>{analysis.last.name}</Link><small>{dateLabel(analysis.last.date)}</small></dd></div></dl><div className="infobox-model"><b>TELEMETRY ONE / ARCHIVO</b><p>1950–2025 · {stats.races} GP de esta marca</p></div></div><p className="ency-aside-note">Datos corporativos revisados en octubre de 2026. El palmarés termina en 2025. Las ubicaciones históricas se identifican expresamente.</p></>;
  return <main id="top" className="ency-page tyre-page"><SiteHeader /><div className="ency-page-wrap"><header className="ency-title"><nav className="ency-breadcrumb" aria-label="Ruta del artículo"><Link href="/historia">Historia</Link><span>/</span><Link href="/historia/neumaticos">Neumáticos</Link><span>/</span><span>{entity.name}</span></nav><p className="ency-eyebrow">FABRICANTE DE NEUMÁTICOS · {entity.firstSeason}–{entity.lastSeason}</p><h1>{entity.name}</h1><p className="ency-subtitle">La empresa, su huella en el campeonato y los materiales detrás del contacto con el asfalto.</p><nav className="tyre-manufacturer-nav" aria-label="Fabricantes de neumáticos">{brands.map(c => <Link key={c.id} href={`/historia/tyres/${c.id}`} aria-current={c.id === entity.id ? 'page' : undefined} prefetch={false}>{c.name}</Link>)}</nav></header><Encyclopedia sections={sections} aside={aside}>
    <EncyclopediaSection id="fabricante" title="El fabricante, de un vistazo" kicker="01 / IDENTIDAD" open><div className="tyre-overview"><TyreBrand company={company} /><dl><div><dt>Fundación</dt><dd>{company.founded}</dd></div><div><dt>Fundador / origen societario</dt><dd>{company.founders}</dd></div><div><dt>{company.locationLabel}</dt><dd>{company.location}</dd></div><div><dt>Primer GP del archivo</dt><dd><Link href={analysis.first.href}>{analysis.first.name} · {analysis.first.year}</Link></dd></div><div><dt>Último GP del archivo</dt><dd><Link href={analysis.last.href}>{analysis.last.name} · {analysis.last.year}</Link></dd></div><div><dt>Mejor clasificación / salida</dt><dd>{analysis.bestFinish ?? '—'} / {analysis.bestGrid ?? '—'}</dd></div></dl></div><div className="tyre-overview-links">{company.website ? <a href={company.website} target="_blank" rel="noreferrer">Sitio oficial ↗</a> : null}<a href={company.wikipedia} target="_blank" rel="noreferrer">Wikipedia ↗</a><a href={`https://www.openstreetmap.org/search?query=${encodeURIComponent(company.location)}`} target="_blank" rel="noreferrer">Ver localidad en el mapa ↗</a></div><div className="tyre-metrics">{metrics.map(([label, value]) => <div key={label}><strong>{number(value)}</strong><span>{label}</span></div>)}</div><p className="ency-note">Inscripciones y participaciones cuentan pilotos; victorias y podios deduplican autos compartidos. No existe un campeonato oficial de fabricantes de neumáticos. Primer y último GP son registros del archivo, incluso si una inscripción no largó.</p></EncyclopediaSection>
    <EncyclopediaSection id="historia" title="Historia, origen y localización" kicker="02 / CONTEXTO" open><p>{company.story}</p><p>{entity.narrative.join(' ')}</p><div className="tyre-location"><span aria-hidden="true">{company.flag}</span><div><h3>{company.locationLabel}</h3><p>{company.location}</p><a href={`https://www.openstreetmap.org/search?query=${encodeURIComponent(company.location)}`} target="_blank" rel="noreferrer">Explorar la localidad ↗</a></div></div><p className="ency-note">La localidad identifica la sede u origen indicado; no todas las plantas de producción. Fuentes: {company.sources.map((s, i) => <span key={s.url}>{i ? ' · ' : ''}<a href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a></span>)}. Síntesis original.</p></EncyclopediaSection>
    <EncyclopediaSection id="estadisticas" title="Resultados y competencia entre proveedores" kicker="03 / ESTADÍSTICAS" open><p>Una victoria con varios fabricantes en pista responde a un contexto distinto de una victoria con proveedor único. Separá las etapas antes de comparar.</p><div className="tyre-mode-grid">{([['multi', 'Varios proveedores'], ['sole', 'Un proveedor'], ['unknown', 'Sin comparación disponible']] as const).map(([key, label]) => <div key={key}><h3>{label}</h3><strong>{number(analysis.modes[key].races)} <small>GP</small></strong><p>{number(analysis.modes[key].wins)} victorias · {analysis.modes[key].races ? percent(analysis.modes[key].wins / analysis.modes[key].races) : '—'} por GP</p></div>)}</div><TyrePerformance analysis={analysis} /></EncyclopediaSection>
    <EncyclopediaSection id="tecnologia" title="Materiales, construcción y propiedades" kicker="04 / TECNOLOGÍA"><TyreTechnology brandId={entity.id} brands={brands} /></EncyclopediaSection>
    <EncyclopediaSection id="conexiones" title="Pilotos, constructores y motores" kicker="05 / CONEXIONES">{(['drivers', 'constructors', 'engines'] as const).map(category => <details key={category} className="tyre-relation"><summary>{category === 'drivers' ? 'Pilotos' : category === 'constructors' ? 'Constructores' : 'Motoristas'} · {relations(category).length}</summary><div className="ency-table-scroll"><table><caption>Asociaciones registradas con {entity.name}</caption><thead><tr><th>Identidad</th><th>GP</th><th>Victorias</th><th>Período</th></tr></thead><tbody>{relations(category).map(r => <tr key={r.id}><th scope="row"><Link href={r.href} prefetch={false}>{r.name}</Link></th><td>{r.races}</td><td>{r.wins}</td><td>{r.firstSeason}–{r.lastSeason}</td></tr>)}</tbody></table></div></details>)}<p className="ency-note">Una conexión indica participación con ese equipamiento. Los logros de pilotos en autos compartidos pueden sumar más que las victorias de la marca.</p></EncyclopediaSection>
    <EncyclopediaSection id="hitos" title="Hitos y temporadas" kicker="06 / CRONOLOGÍA"><ol className="tyre-timeline">{entity.milestones.map(m => <li key={`${m.label}/${m.date}`}><time>{m.date ? dateLabel(m.date) : m.season}</time><strong>{m.label}</strong><span>{m.event}</span><Link href={`/historia/seasons/${m.season}`}>Temporada {m.season} →</Link></li>)}</ol><p>Temporadas documentadas: {periods(entity.seasons.map(s => s.season))}.</p></EncyclopediaSection>
    <EncyclopediaSection id="fuentes" title="Fuentes, cobertura y método" kicker="07 / REFERENCIAS"><ul className="ency-sources"><li><a href="https://github.com/f1db/f1db" target="_blank" rel="noreferrer">F1DB · CC BY 4.0</a>: resultados, inscripciones y sesiones, 1950–2025. Incluye Indianápolis 1950–1960.</li><li><a href={company.wikipedia} target="_blank" rel="noreferrer">Wikipedia · {entity.name}</a>: contexto y distinción entre marca y sociedad histórica.</li>{company.sources.map(s => <li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a>: hechos corporativos.</li>)}<li><a href="https://www.statsf1.com/es/pneus.aspx" target="_blank" rel="noreferrer">StatsF1 · neumáticos</a>: referencia del formato; los totales mostrados se calculan desde nuestro archivo.</li><li>Las propiedades técnicas usan documentación de fabricantes enlazada por fila, con alcance industrial o de carretera. No se presentan recetas ni durezas de F1 sin documentación comparable.</li></ul><p>La competencia usa fabricantes de las largadas registradas por GP: varios conocidos indican competencia; uno solo sin identidades desconocidas indica un proveedor. Si la marca no largó o falta información, queda sin comparación. Es una clasificación de los registros de carrera, no una reconstrucción de contratos de exclusividad.</p><p>Las poles se cuentan desde el registro de la pole del GP. La posición de salida puede diferir por sanciones y reglas sprint. No calculamos puntos de campeonato de neumáticos.</p><p>TelemetryOne no identifica por separado un efecto químico del neumático. No atribuimos a la marca el ELO de sus pilotos ni interpretamos sus victorias como una prueba causal de calidad de los materiales.</p><a href="/history/tyre-analysis.json" target="_blank" rel="noreferrer">Estadísticas y metodología (JSON) ↗</a></EncyclopediaSection>
  </Encyclopedia></div><SiteFooter /></main>;
}
