"use client";

import { useId, useState } from 'react';
import Link from 'next/link';
import { tyreMaterialSources } from '@/lib/tyre-materials';

const materials = [
  { name: 'Cauchos', title: 'La matriz elástica', text: 'Cauchos naturales y sintéticos forman la base elástica. Su mezcla participa en la respuesta al contacto y la deformación. Una misma familia de material admite formulaciones distintas.', color: '#c65743' },
  { name: 'Cargas', title: 'Refuerzo de la mezcla', text: 'Negro de carbono y sílice pueden reforzar la mezcla y modificar su respuesta al desgaste o a superficies mojadas. Saber que se utiliza un material no revela su proporción ni permite comparar el agarre de dos neumáticos.', color: '#597388' },
  { name: 'Vulcanización', title: 'Estabilizar la estructura elástica', text: 'El azufre y otros agentes intervienen en la vulcanización. El proceso estabiliza la mezcla y sus propiedades elásticas. La receta y las condiciones de fabricación dependen del producto.', color: '#b08a32' },
  { name: 'Refuerzos', title: 'La estructura que sostiene las cargas', text: 'Cordones textiles y elementos metálicos refuerzan partes del neumático según el diseño. Los talones lo fijan a la llanta. Estos principios explican la construcción industrial, sin reconstruir un plano de competición.', color: '#527d64' }
];
export function TyreTechnology({ brandId, brands }: { brandId: string; brands: { id: string; name: string }[] }) {
  const [material, setMaterial] = useState(0);
  const diagramId = useId();
  const source = tyreMaterialSources[brandId];
  return <div className="tyre-technology">
    <p>La comparación reúne documentación de materiales para <strong>{Object.keys(tyreMaterialSources).length} de los {brands.length} fabricantes</strong> del archivo. Compara familias de materiales y construcción, con el mismo criterio para todas las marcas.</p>
    <div className="tyre-coverage-note"><strong>Alcance industrial, no fórmula de F1.</strong><p>Las fuentes describen neumáticos de carretera o materiales industriales y llevan su alcance indicado. No publican una receta comparable de los compuestos históricos de F1. La presencia de un ingrediente no informa su concentración.</p></div>
    <h3>Materiales documentados por fabricante</h3><div className="ency-table-scroll"><table><caption>Familias de materiales · fuentes públicas de fabricantes</caption><thead><tr><th>Fabricante</th><th>Base elástica</th><th>Cargas</th><th>Refuerzos</th><th>Producto / alcance y fuente</th></tr></thead><tbody>{brands.map(brand => { const row = tyreMaterialSources[brand.id]; return <tr key={brand.id} className={brand.id === brandId ? 'tyre-current-row' : undefined}><th scope="row"><Link href={`/historia/tyres/${brand.id}`} prefetch={false}>{brand.name}</Link>{brand.id === brandId ? <small>Esta ficha</small> : null}</th><td>{row?.rubber ?? 'Sin documentación contrastada'}</td><td>{row?.fillers ?? 'Sin documentación contrastada'}</td><td>{row?.structure ?? 'Sin documentación contrastada'}</td><td>{row ? <>{row.scope}{row.urls.map((url, i) => <small key={url}><a href={url} target="_blank" rel="noreferrer">Fuente {i + 1} ↗</a></small>)}</> : 'No inferido a partir de otras marcas'}</td></tr>; })}</tbody></table></div>
    <p className="ency-note">«Sin documentación contrastada» significa que no se verificó ese dato para esta ficha; no que la marca no utilizara el material. No se trasladan materiales actuales a neumáticos históricos.</p><p>{source ? <>Para esta marca: {source.scope}. Los datos corresponden a los productos descritos en sus fuentes; no a todos sus neumáticos ni a una temporada específica de F1.</> : 'Esta marca tiene estadísticas deportivas, pero no una especificación de materiales contrastada en esta comparación.'}</p>
    <h3>Explorar composición y construcción</h3><div className="tyre-material-explorer"><figure><svg viewBox="0 0 340 270" role="img" aria-labelledby={diagramId}><title id={diagramId}>Esquema conceptual de banda, refuerzos, flancos y talones; no es un diseño específico de marca o de F1.</title><path d="M70 240 L70 98 Q70 35 125 35 H215 Q270 35 270 98 V240 L245 240 V103 Q245 70 215 70 H125 Q95 70 95 103 V240 Z" fill="#252e36"/><path d="M70 98 Q70 35 125 35 H215 Q270 35 270 98 L245 103 Q245 70 215 70 H125 Q95 70 95 103 Z" fill={materials[material].color}/><path d="M84 226 V102 Q84 52 125 52 H215 Q257 52 257 102 V226" fill="none" stroke="#b1c0ca" strokeWidth="4" strokeDasharray="5 4"/><circle cx="83" cy="235" r="10" fill="#d9e0e6"/><circle cx="257" cy="235" r="10" fill="#d9e0e6"/><text x="170" y="23" textAnchor="middle">Banda de rodadura</text><text x="170" y="132" textAnchor="middle">Carcasa / refuerzos</text><text x="170" y="186" textAnchor="middle">Flancos</text><text x="170" y="250" textAnchor="middle">Talones</text></svg><figcaption>Esquema didáctico · sin escala · arquitectura general</figcaption></figure><div><div className="tyre-controls" role="group" aria-label="Material del neumático">{materials.map((m, i) => <button key={m.name} aria-pressed={material === i} onClick={() => setMaterial(i)}>{m.name}</button>)}</div><div aria-live="polite"><h4>{materials[material].title}</h4><p>{materials[material].text}</p></div><p className="ency-note">Principios de <a href="https://www.continental-tires.com/au/en/tyre-knowledge/tire-mixture/" target="_blank" rel="noreferrer">Continental ↗</a>, <a href="https://continentaltire.com/learn/how-build-radial-tire" target="_blank" rel="noreferrer">fabricación radial ↗</a> y <a href="https://www.bridgestone.com/products/basic_knowledge/materials/" target="_blank" rel="noreferrer">Bridgestone ↗</a>. Ilustración conceptual propia.</p></div></div>
    <h3>Propiedades físicas: un criterio común para las nueve marcas</h3><div className="ency-table-scroll"><table><caption>Propiedades comparables y cobertura del archivo de F1</caption><thead><tr><th>Propiedad</th><th>Qué habría que medir</th><th>Disponibilidad comparable en F1</th></tr></thead><tbody><tr><th scope="row">Dureza</th><td>Escala, temperatura y procedimiento de ensayo</td><td>No documentada para la mayoría</td></tr><tr><th scope="row">Rigidez</th><td>Respuesta a carga, presión y temperatura controladas</td><td>No documentada para la mayoría</td></tr><tr><th scope="row">Resistencia al desgaste</th><td>Ensayo equivalente por producto y época</td><td>No documentada para la mayoría</td></tr><tr><th scope="row">Composición porcentual</th><td>Masa por material y componente del neumático</td><td>No documentada para la mayoría</td></tr></tbody></table></div><p>Esas propiedades quedan sin puntuación ni ranking. Una tabla numérica sería útil sólo con ensayos equivalentes y cobertura suficiente; el nombre de un fabricante y su palmarés no permiten reconstruirla.</p><p className="ency-note">Documentación revisada el 5 de octubre de 2026. El archivo deportivo conserva su corte de 2025.</p>
  </div>;
}
